# Generated by Django 4.2.5 on 2023-09-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('nif', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
